# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAuto < Formula
  desc ""
  homepage ""
  version "1.2.1"

  on_macos do
    url "https://github.com/s-matsubara/git-auto/releases/download/1.2.1/git-auto_1.2.1_darwin_all.tar.gz"
    sha256 "ae87be118b705c20c05cdd24278cef1463013df32bdf38eef73b8ae113cbb5ae"

    def install
      bin.install "git-auto"
      bash_completion.install "completions/git-auto.bash" => "git-auto"
      zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
      fish_completion.install "completions/git-auto.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.1/git-auto_1.2.1_linux_amd64.tar.gz"
      sha256 "3bd836fe4a32539fc068572338cd23a5681ca4bfced47a21194422f4558c6956"
      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.1/git-auto_1.2.1_linux_arm64.tar.gz"
      sha256 "bea3b382edcf8a8917abbb166518ab517e5da108271032b1b788bf054a1275e3"
      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
  end

  def caveats
    <<~EOS
      If you want to register for git alias:

        git config --global alias.auto '!git-auto'
        git config --global alias.mergedd '!git-auto delete-merged-branch'
        git config --global alias.auto-tag '!git-auto tag'

      To see how to use:

        git-auto -h
    EOS
  end
end
