# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAuto < Formula
  desc ""
  homepage ""
  version "1.1.5"

  on_macos do
    url "https://github.com/s-matsubara/git-auto/releases/download/1.1.5/git-auto_1.1.5_darwin_all.tar.gz"
    sha256 "67f908887d0f0a3048ab236fac9138f9a913708930bb3465394498b4489c6fb1"

    def install
      bin.install "git-auto"
      bash_completion.install "completions/git-auto.bash" => "git-auto"
      zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
      fish_completion.install "completions/git-auto.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.1.5/git-auto_1.1.5_linux_amd64.tar.gz"
      sha256 "d035a69b532b157d957fb68a3a42fdd4dea64d348baa0c9e01f5d919768a816c"
      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.1.5/git-auto_1.1.5_linux_arm64.tar.gz"
      sha256 "f32f55c38741ff85238665ee39d6c0ecb22da232ce95e28cdd1a36b9d1da82cb"
      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
  end

  def caveats
    <<~EOS
      If you want to register for git alias:

        git config --global alias.auto '!git-auto'
        git config --global alias.mergedd '!git-auto delete-merged-branch'
        git config --global alias.auto-tag '!git-auto tag'

      To see how to use:

        git-auto -h
    EOS
  end
end
