# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAuto < Formula
  desc ""
  homepage ""
  version "1.2.0"

  on_macos do
    url "https://github.com/s-matsubara/git-auto/releases/download/1.2.0/git-auto_1.2.0_darwin_all.tar.gz"
    sha256 "62fa6aa6c79c76297460c3107ac3bd2e84c4c4849d60fd050ca6868d71db95e8"

    def install
      bin.install "git-auto"
      bash_completion.install "completions/git-auto.bash" => "git-auto"
      zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
      fish_completion.install "completions/git-auto.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.0/git-auto_1.2.0_linux_amd64.tar.gz"
      sha256 "b1ca1db44bce7ec1cea6610ae9f90e126ba5399e6c97fcb6af7b1d0cf597c25b"
      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.0/git-auto_1.2.0_linux_arm64.tar.gz"
      sha256 "697d4c7932fd41256b2f6be44670b513927df56a83c645afc9c738ee0523b49e"
      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
  end

  def caveats
    <<~EOS
      If you want to register for git alias:

        git config --global alias.auto '!git-auto'
        git config --global alias.mergedd '!git-auto delete-merged-branch'
        git config --global alias.auto-tag '!git-auto tag'

      To see how to use:

        git-auto -h
    EOS
  end
end
