# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PubsubCli < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.0/pubsub-cli_Darwin_x86_64.tar.gz"
      sha256 "341cbc188c52e2c3d1b82ef75b490b6a647f0b2cade6df041dc14ef09c7db9fe"

      def install
        bin.install "pubsub-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.0/pubsub-cli_Darwin_arm64.tar.gz"
      sha256 "c51e11d684fe3a449180a50b02f9ecdf73da1c87fb4829e588c06950294fc36c"

      def install
        bin.install "pubsub-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.0/pubsub-cli_Linux_arm64.tar.gz"
      sha256 "5a125a6c719a71663d7af35e73ce868276683bc15b9aedf55b6ccb65e7fa60c3"

      def install
        bin.install "pubsub-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.0/pubsub-cli_Linux_x86_64.tar.gz"
      sha256 "0a62155eb867023f94691a89d437c889078bd56074872d1658d92718d8230e3d"

      def install
        bin.install "pubsub-cli"
      end
    end
  end
end
