# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestCli < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.0.2/test-cli_Darwin_x86_64.tar.gz"
      sha256 "84fb1a2cf024507619d4fec62d797522a799275beb6e71929bfa9e6515779755"

      def install
        bin.install "test-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.0.2/test-cli_Darwin_arm64.tar.gz"
      sha256 "c30db938be1072b9ff3c765687972f10d108fec536f00a841556af4fea920315"

      def install
        bin.install "test-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.0.2/test-cli_Linux_x86_64.tar.gz"
      sha256 "a34d0c92a563d3d2f5cce793d3b6ab12fd7f87e606ce20093b4dbcfd1242e6af"

      def install
        bin.install "test-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.0.2/test-cli_Linux_arm64.tar.gz"
      sha256 "43b4173ad32b75aca2a58d369690d1cd2d816cf5e0c2236d9076514b7d5867aa"

      def install
        bin.install "test-cli"
      end
    end
  end
end
