# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-auto" do
  desc ""
  homepage ""
  version "1.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-auto"
  bash_completion "completions/git-auto.bash"
  zsh_completion "completions/git-auto.zsh"
  fish_completion "completions/git-auto.fish"

  on_macos do
    url "https://github.com/s-matsubara/git-auto/releases/download/1.2.3/git-auto_1.2.3_darwin_all.tar.gz"
    sha256 "2928f6f5b259ebdd82e8b1c724f8414738bedf15691e56e992a17603a0dbf2ec"
  end

  on_linux do
    on_intel do
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.3/git-auto_1.2.3_linux_amd64.tar.gz"
      sha256 "3f2460b4c7bd52f3f4f6f891405fc7f35fafca44187ea4527189fc824cee66f6"
    end
    on_arm do
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.3/git-auto_1.2.3_linux_arm64.tar.gz"
      sha256 "09b93221249d1eaec2ac6180548cb36e2d4cab47e57160979bbbe940ffd76832"
    end
  end

  caveats do
    "If you want to register for git alias:"
    ""
    "  git config --global alias.auto '!git-auto'"
    "  git config --global alias.mergedd '!git-auto delete-merged-branch'"
    "  git config --global alias.auto-tag '!git-auto tag'"
    ""
    "To see how to use:"
    ""
    "  git-auto -h"
  end

  # No zap stanza required
end
