# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-auto" do
  desc ""
  homepage ""
  version "1.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-auto"
  bash_completion "completions/git-auto.bash"
  zsh_completion "completions/git-auto.zsh"
  fish_completion "completions/git-auto.fish"

  on_macos do
    url "https://github.com/s-matsubara/git-auto/releases/download/1.2.4/git-auto_1.2.4_darwin_all.tar.gz"
    sha256 "cdc452c434ee55bd7124fc6a346ecd3964f213db9450d61b726fd5ee384ab5f8"
  end

  on_linux do
    on_intel do
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.4/git-auto_1.2.4_linux_amd64.tar.gz"
      sha256 "a2eda00d87ebeab5557d0046c9eda5170ab2d37e3228e1bbb5917b4ef6a4c868"
    end
    on_arm do
      url "https://github.com/s-matsubara/git-auto/releases/download/1.2.4/git-auto_1.2.4_linux_arm64.tar.gz"
      sha256 "aab5d420778430ec6b786318f06a894c9887d8b95a63987a376cc06a563ae023"
    end
  end

  caveats do
    "If you want to register for git alias:"
    ""
    "  git config --global alias.auto '!git-auto'"
    "  git config --global alias.mergedd '!git-auto delete-merged-branch'"
    "  git config --global alias.auto-tag '!git-auto tag'"
    ""
    "To see how to use:"
    ""
    "  git-auto -h"
  end

  # No zap stanza required
end
