# This file was generated by GoReleaser. DO NOT EDIT.
cask "test-cli" do
  desc ""
  homepage ""
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "test-cli"

  on_macos do
    on_intel do
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.4/test-cli_0.2.4_darwin_amd64.tar.gz"
      sha256 "8e37c4204747f3cdae1b19c4abf54b499db8fa7ed2b89a13773898bbaf6565e1"
    end
    on_arm do
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.4/test-cli_0.2.4_darwin_arm64.tar.gz"
      sha256 "dd35fe6c83bc2450587aceb1581b81a44a942cbeea49c604fe60267103a5ed64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.4/test-cli_0.2.4_linux_amd64.tar.gz"
      sha256 "ca74beb8e106132a9c9478206b55dbc2824275df9d759f8e9415a1efb1dc158e"
    end
    on_arm do
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.4/test-cli_0.2.4_linux_arm64.tar.gz"
      sha256 "0e54941eb1232f2b771eb94e1de3add962f3ce51563af7a65236e8d6add03086"
    end
  end

  # No zap stanza required
end
