# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAuto < Formula
  desc ""
  homepage ""
  version "1.1.3"

  on_macos do
    url "https://github.com/s-matsubara/git-auto/releases/download/1.1.3/git-auto_Darwin_all.tar.gz"
    sha256 "e71701e5965d8ff8123851b4ea76f8a71055a89696672960b3423bbf27398963"

    def install
      bin.install "git-auto"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.1.3/git-auto_Linux_arm64.tar.gz"
      sha256 "c69cc485267972252df0dd4b61b6a25b1c9468542918a2aa6692b4a3ab1d48b7"

      def install
        bin.install "git-auto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.1.3/git-auto_Linux_x86_64.tar.gz"
      sha256 "17123de9df90d75c97cb94e422b40310a4754a8703818822cea29312b3bf316b"

      def install
        bin.install "git-auto"
      end
    end
  end

  def caveats
    <<~EOS
      If you want to register for git alias:

        git config --global alias.auto '!git-auto'
        git config --global alias.mergedd '!git-auto delete-merged-branch'
        git config --global alias.auto-tag '!git-auto tag'

      To see how to use:

        git-auto -h
    EOS
  end
end
