# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAuto < Formula
  desc ""
  homepage ""
  version "1.1.4"

  on_macos do
    url "https://github.com/s-matsubara/git-auto/releases/download/1.1.4/git-auto_Darwin_all.tar.gz"
    sha256 "ed2d59dab9c2214f2ac742e57a4789c063d122e77abf2130320a9409096646e3"

    def install
      bin.install "git-auto"
      bash_completion.install "completions/git-auto.bash" => "git-auto"
      zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
      fish_completion.install "completions/git-auto.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.1.4/git-auto_Linux_x86_64.tar.gz"
      sha256 "a9bb2a6d1c268fe7f62700c9fe362f1c93c8154ca37648fdfa08b3c11676c385"

      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/git-auto/releases/download/1.1.4/git-auto_Linux_arm64.tar.gz"
      sha256 "12be7896565ddecf9e30959e0d8e922dd2148000680997aa089bd00554ae28fe"

      def install
        bin.install "git-auto"
        bash_completion.install "completions/git-auto.bash" => "git-auto"
        zsh_completion.install "completions/git-auto.zsh" => "_git-auto"
        fish_completion.install "completions/git-auto.fish"
      end
    end
  end

  def caveats
    <<~EOS
      If you want to register for git alias:

        git config --global alias.auto '!git-auto'
        git config --global alias.mergedd '!git-auto delete-merged-branch'
        git config --global alias.auto-tag '!git-auto tag'

      To see how to use:

        git-auto -h
    EOS
  end
end
