# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PubsubCli < Formula
  desc ""
  homepage ""
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.2/pubsub-cli_Darwin_x86_64.tar.gz"
      sha256 "15197cb3a83b6214f0974d4acd509b3cc0102b9e4c14dc1ff475c26f3acd83d8"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.2/pubsub-cli_Darwin_arm64.tar.gz"
      sha256 "e068d2c337edeb06a86bdcf8f3ee9127c6470ebd167e2184bd1ca986a6cb89d3"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.2/pubsub-cli_Linux_arm64.tar.gz"
      sha256 "64cbf453f0e8ec4be65cfe3ccd94a5c8eacb8a4d7ccb4e8fe0536c36050acfc5"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.2/pubsub-cli_Linux_x86_64.tar.gz"
      sha256 "061b2fecfdba709b94f6785b83e162a8eab6bd993380e72253cba6c919422a85"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
  end
end
