# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PubsubCli < Formula
  desc ""
  homepage ""
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.3/pubsub-cli_Darwin_x86_64.tar.gz"
      sha256 "93f129b20bf42309e187c54380d272a711251a90f52e14703c7eb780326da074"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.3/pubsub-cli_Darwin_arm64.tar.gz"
      sha256 "44f4bccaef3433bb9cf73d6dde9014c4fc02a0de9bc5a8562e00a31b5095eb1a"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.3/pubsub-cli_Linux_arm64.tar.gz"
      sha256 "3ca2f10bb142ef3fddb2358a03d2ea05e08a3244e123fb5b81e7f506c5c959a8"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/pubsub-cli/releases/download/1.0.3/pubsub-cli_Linux_x86_64.tar.gz"
      sha256 "16d22a68f26622ad16cf228530973825094dbb241a589c2643d7673ed268da63"

      def install
        bin.install "pubsub-cli"
        bash_completion.install "completions/pubsub-cli.bash" => "pubsub-cli"
        zsh_completion.install "completions/pubsub-cli.zsh" => "_pubsub-cli"
        fish_completion.install "completions/pubsub-cli.fish"
      end
    end
  end
end
