# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestCli < Formula
  desc ""
  homepage ""
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.1/test-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "9b53867215c438d279e8b20e668d935bdc4a30cdf3329d2952b35728dd9f392e"

      def install
        bin.install "test-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.1/test-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "455051c569cd69f0f5191a97a69d3f9808b81b26b96eb186de46dfb3b3051b14"

      def install
        bin.install "test-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/s-matsubara/test-cli/releases/download/0.2.1/test-cli_0.2.1_linux_amd64.tar.gz"
        sha256 "99d74f0beebcfb0acce947f3358e3115ed0a021d942fb530f32225e8238ca892"

        def install
          bin.install "test-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/s-matsubara/test-cli/releases/download/0.2.1/test-cli_0.2.1_linux_arm64.tar.gz"
        sha256 "f8947c2eac61364fc6ca7e3646fdea2d86edd46464c2f00907fb985d948ce404"

        def install
          bin.install "test-cli"
        end
      end
    end
  end
end
