# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestCli < Formula
  desc ""
  homepage ""
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.2/test-cli_0.2.2_darwin_amd64.tar.gz"
      sha256 "42dd02588fc133ae72e26b8307a702acf000574a457648baa3e366d5c21e16dc"

      def install
        bin.install "test-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.2/test-cli_0.2.2_darwin_arm64.tar.gz"
      sha256 "1beb61c37df4d90475e0ccfdb14cf410ac43b6f7f5dd17d4f006638461902c3b"

      def install
        bin.install "test-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.2/test-cli_0.2.2_linux_amd64.tar.gz"
      sha256 "e43c0adaa9ca336666e8ca79aaec7ee13eedfda43f85f33000ec6ca23123baba"
      def install
        bin.install "test-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/s-matsubara/test-cli/releases/download/0.2.2/test-cli_0.2.2_linux_arm64.tar.gz"
      sha256 "e71adc4b235c3d7417f2ee8eba88821a209f3e3e58c570f812098fcf9985b7a5"
      def install
        bin.install "test-cli"
      end
    end
  end
end
